keys:
  # YubiKey identities (from secret/secrets.nix)
  - &yubikey-keychain-a age1yubikey1q0w4elvpyp83lnat0hce5247rvuvmjnx2d670t0qp07447rxqyulx7tpv2r
  - &yubikey-folder-b age1yubikey1qwqyr54w5yseu8lwusqr9tvxm8e30tv7mn3xf4swjaq6r383985k5t7fp3y
  - &yubikey-laptop-c age1yubikey1qf95j5rtmv2tunv0a4f2qecnej37zsegy840g38aq5hvzcehv2d6jqpyvzw

  # Host keys
  - &host-bartleby age1s3m5g0rl7rr4ueuxqv7v9m2wu3emt5fr5xt7pst7y58cydrldclst5gmkv
  - &host-abigail age10nheqdle9xweuh9xy67jml8s4w2tafe5heyzcuhjn48rgk23hgtsx63dxg
  - &host-toph age1n8yyuq4myev2d5zuf6ae3f96wzs3s9j5llgrnalc4zhw2398vccsrqrweq
  - &host-clementine age1udh3pf6lch8sncjqe34dr82aa9ufff269tvpmw43gm0ggwdxrspsgyclpc

creation_rules:
  - path_regex: secret/.*\.json$
    key_groups:
      - age:
          - *yubikey-keychain-a
          - *yubikey-folder-b
          - *yubikey-laptop-c
          - *host-bartleby
          - *host-abigail
          - *host-toph
          - *host-clementine
