" Standard Settings
syntax on
set re=0
filetype plugin indent on
colorscheme noctu

set exrc
set nocompatible
set background=dark
set expandtab
set hidden
set mouse=a
set number
set relativenumber
set shiftwidth=2
set tabstop=2
set undofile
set backspace=indent,eol,start
set softtabstop=2
set textwidth=80
set autowrite
set autowriteall
set autoread
set showcmd
set laststatus=2
set showtabline=2
set guioptions-=e
set splitbelow splitright
set backupdir=~/.local/vim/backup//,/tmp//
set directory=~/.local/vim/swp//,/tmp//
set undodir=~/.local/vim/undo//,/tmp//

" Leader mapping
map <Space> <Leader>

" Custom unimpaired mappings for jumping between windows
nmap [w <C-W>w
nmap ]w <C-W>W

" Fuzzy file finding
set path=$PWD/**
set wildmenu
set wildignore+=**/.git/**,**/node_modules/**,**/result/**,**/dist/**,**/build/**

" Use ripgrep for grep when we can
if executable("rg")
  set grepprg=rg\ --vimgrep\ --smart-case\ --hidden
  set grepformat=%f:%l:%c:%m
endif

" Tab through omnifunc
function! Tab()
  if (pumvisible())
    return "\<C-N>"                         " existing text matching
  else
    return "\<Tab>"                         " plugin matching
  endif
endfunction

function! ShiftTab()
  if (pumvisible())
    return "\<C-P>"                         " existing text matching
  else
    return "\<S-Tab>"                         " plugin matching
  endif
endfunction

inoremap <Tab> <c-r>=Tab()<CR>
inoremap <S-Tab> <c-r>=ShiftTab()<CR>

" Ledger settings
let g:ledger_is_hledger = 1

" vim-lsp settings
function! s:on_lsp_buffer_enabled() abort
    setlocal omnifunc=lsp#complete
    setlocal signcolumn=yes
    if exists('+tagfunc') | setlocal tagfunc=lsp#tagfunc | endif
    nmap <buffer> gd <plug>(lsp-definition)
    nmap <buffer> gs <plug>(lsp-document-symbol-search)
    nmap <buffer> gS <plug>(lsp-workspace-symbol-search)
    nmap <buffer> gr <plug>(lsp-references)
    nmap <buffer> gi <plug>(lsp-implementation)
    nmap <buffer> gt <plug>(lsp-type-definition)
    nmap <buffer> <leader>rn <plug>(lsp-rename)
    nmap <buffer> [g <plug>(lsp-previous-diagnostic)
    nmap <buffer> ]g <plug>(lsp-next-diagnostic)
    nmap <buffer> K <plug>(lsp-hover)
    nnoremap <buffer> <expr><c-f> lsp#scroll(+4)
    nnoremap <buffer> <expr><c-d> lsp#scroll(-4)
    imap <c-space> <Plug>(asyncomplete_force_refresh)

    let g:lsp_format_sync_timeout = 1000
    autocmd! BufWritePre * call execute('LspDocumentFormatSync')
    
    " refer to doc to add more commands
endfunction

augroup lsp_install
    au!
    " call s:on_lsp_buffer_enabled only for languages that has the server registered.
    autocmd User lsp_buffer_enabled call s:on_lsp_buffer_enabled()
augroup END

